export interface SiteConfig {
  site_name: string;
  site_subtitle: string;
  site_description: string;
  site_keywords: string;
  site_logo: string;
  site_favicon: string;
  user_registration_enabled: boolean;
  user_email_verification: boolean;
  comment_approval_required: boolean;
  article_approval_required: boolean;
  payment_alipay_enabled: boolean;
  payment_wechat_enabled: boolean;
  payment_epay_enabled: boolean;
  membership_enabled: boolean;
  membership_name: string;
  membership_price: number;
  maintenance_mode: boolean;
  maintenance_message: string;
  invite_code_required: boolean;
  invite_code_enabled: boolean;
  invite_default_commission_rate: number;
  invite_code_expire_days: number;
  // 新增配置项
  commission_author_rate: number;
  commission_platform_rate: number;
  payment_alipay_app_id: string;
  payment_alipay_private_key: string;
  payment_alipay_public_key: string;
  payment_wechat_app_id: string;
  payment_wechat_api_key: string;
  payment_wechat_mch_id: string;
  payment_epay_pid: string;
  payment_epay_key: string;
  payment_epay_notify_url: string;
  payment_epay_return_url: string;
}
